language: node_js

node_js:
    - 13

branches:
    only:
        - master
cache:
    directories:
        - node_modules
install:
    - travis_retry yarn

script:
    - yarn bootstrap
    - yarn lint
    - yarn test
    - yarn build:docs
    - yarn build:components

jobs:
    include:
        - stage: release
          node_js: lts/*
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - yarn gh-pages --repo "https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG" -t -d docs && yarn semantic-release

notifications:
    email: false
